### ISSUE TITLE
Yagi not supported for IDA interactive debugging

### ISSUE THREAD

**Issue by aaaddress1** [airbus-cert/Yagi#5]
Hi there,

IDA allow users to analyze between static & debugging. however, Yagi use F7 as hotkey, it will let users cannot do single-step in dynamic mode. besides, Yagi is not stable and easy to crash in dynamic mode :(

**Comment by citronneur** [comment]
Hello,

Thanks for your feedback, indeed I changed because on linux i had some strange behavior with my first choice. I will switch to F3 key that seems to free for both distrubution.

Could you be more explicit vy "Yagi is not stable and easy to crash in dynamic mode" please?

Have a nice day,

Sylvain

**Comment by citronneur** [comment]
Done in last release, please open another issur for crash.
Now decomilation is available using **F3** key!
Have a nice day!
